### ISSUE TITLE
Alignment of Two column in EoC for sections with subtitles

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2153]
In two columns layout both should start on the same baseline.
![Screenshot from 2020-04-03 14-50-46](https://user-images.githubusercontent.com/47241114/78362648-c18f9200-75ba-11ea-81be-bdace56de49a.png)

**Comment by lwtchu** [comment]
Should be fixed.

It currently works if there are no sub headers - but it should be starting at the same base line and give room for any title above it.

**Comment by brittweinstein** [comment]
@MartaSztuka please confirm that this is fixed

**Comment by MartaSztuka** [comment]
@brittweinstein without sub headers it ok
![Screenshot from 2020-04-06 10-44-58](https://user-images.githubusercontent.com/47241114/78540007-c1c6a200-77f3-11ea-8dd7-5c78994d325a.png)
with sub headers it's not fixed (baked on carnival100)
![Screenshot from 2020-04-06 10-47-02](https://user-images.githubusercontent.com/47241114/78540141-f9cde500-77f3-11ea-9d8f-719c6c3ed4d6.png)

**Comment by lwtchu** [comment]
Please have the columns align with subtitles like they do in sections without subtitles.

**Comment by MartaSztuka** [comment]
HS Physics![Screenshot from 2020-04-20 14-18-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3ec6220d-dc38-4fef-abf2-7aa891949efa)
