### ISSUE TITLE
Class on <entry> in CNXML gets stripped when transformed into HTML

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3845]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know [x] Neither 

When I put a class on the (table) `<entry>` tag for #3839, the class gets removed once it gets assembled. We need to fix the transforms to have it not strip and add the class on the `<td>`.

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
yes. every time

# Sample mark up if applicable
https://legacy-content04.cnx.org/content/m10024/latest/?collection=col10008/latest - I threw some in here 

# Acceptance Criteria

# Bug Location(s)
collection ID: col10008
server: content04
chapter/section: the gathering and organizing data section has some strewn about.
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
@LostMojo take point, @kswanson33 to :pear:

**Comment by LostMojo** [comment]
Fixed bug on rhaptos.cnxmlutils, the xls wasn't matching classes properly and deleting them.

**Comment by LostMojo** [comment]
The [commit where it was fixed](https://github.com/openstax/rhaptos.cnxmlutils/commit/2e2f9a0358425d9f82355fea370f7c93dcb5bf20)

**Comment by Stackblocks** [comment]
Fix applied directly to master with test content part of an in-development branch. Next time the dev branch updates from master i'll give this a test.

**Comment by Stackblocks** [comment]
Tested with current state of branch 2021-05-19, the `gray-background` class is not present in the contemporary math test content post-assembly. So either the fix isn't present in the branch used for testing, or it isn't working. I'll need to look into this to narrow down which it is.

![2021-05-19_10-58-35](https://user-images.githubusercontent.com/12678235/118845596-866d2280-b891-11eb-873c-8fb1e6a11406.png)

**Comment by Stackblocks** [comment]
Karina updated her contemporary math working branch with the fix code for this but I'm still not seeing the any remnants of `class=gray-shading`

@LostMojo Did you & Phil happen to grab an example of this working when verifying the fix? I'll keep checking to make sure i'm not missing something on my end.

![image](https://user-images.githubusercontent.com/12678235/119404746-d8ed7b00-bca5-11eb-8fff-5aedb4d6db56.png)

**Comment by Stackblocks** [comment]
Karina rebased her working branch off of k.k. milestone, which should include the point on master where this was fixed, but I'm still not seeing any change in the locally baked output file. No remnant of `class=gray-shading` on the table in question.

@LostMojo do you happen to have an example of this working from when you and Phil were doing the work? I can use that to try and diagnose if it's a local issue.

@lwtchu do you have an example of how this should look from a design perspective? I want to make sure i'm not expecting something that isn't going to be there.

![image](https://user-images.githubusercontent.com/12678235/119413976-499b9400-bcb4-11eb-8a76-6be973ef67f9.png)

**Comment by LostMojo** [comment]
![Screen Shot 2021-05-26 at 4 09 32 PM](https://user-images.githubusercontent.com/5740972/119731617-c6597a00-be3c-11eb-87ea-02455d9db6f5.png)


![Screen Shot 2021-05-26 at 4 07 42 PM](https://user-images.githubusercontent.com/5740972/119731496-a033da00-be3c-11eb-93a3-82b7e5ea68db.png)

After we made the changes, it kept the classes on td and th? I don't think we tested for rows, so maybe that's it?

**Comment by LostMojo** [comment]
Here's where 'table-data' shows up

![Screen Shot 2021-05-26 at 4 12 33 PM](https://user-images.githubusercontent.com/5740972/119731991-3c5de100-be3d-11eb-9b2c-f85bf9fa39f1.png)
