### ISSUE TITLE
Numbering in Review Exercises and Practice Test

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#923]
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:FzKp--aR@8.1/Practice-Test
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:XU_EPhae@11.1/Practice-Test
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:3nhouCF9@8.1/Practice-Test
![pt](https://user-images.githubusercontent.com/47241114/54200984-d8a1a480-44cc-11e9-8aa8-d49567e27db5.jpeg)

Issue is in all books, also effects Answer Key.

**Comment by MartaSztuka** [comment]
Figure Numbering doesn't match PDF in **EOC**
https://katalyst01.cnx.org/contents/_VPq4foj@8.4:Q0dD29cN@8.4/Review-Exercises
![asdfghjkl](https://user-images.githubusercontent.com/47241114/55404432-294e6f80-5558-11e9-825f-bfc57c1bc551.jpeg)

**Comment by MartaSztuka** [comment]
Exercises numbering is fixed & tested in all 3 books.
@openstaxalina can I close the issue?
![sdgSRrhbeh](https://user-images.githubusercontent.com/47241114/55551043-1a8fc600-56da-11e9-80ed-3c13fd154655.jpeg)

**Comment by openstaxalina** [comment]
@MartaSztuka I do not see the correct (restarted) numbering in the Review Questions or Practice Test on webview.  Here are screenshots from _Precalculus_:
<img width="1405" alt="Screen Shot 2019-04-04 at 11 58 19 AM" src="https://user-images.githubusercontent.com/7863733/55574032-009db580-56d1-11e9-809a-976169d5fd25.png">
<img width="1440" alt="Screen Shot 2019-04-04 at 11 54 30 AM" src="https://user-images.githubusercontent.com/7863733/55573922-c9c79f80-56d0-11e9-9663-6e1b72378175.png">

I tried testing with cleared browser cache, but I still see the numbering mismatch.

Would you mind rebaking and retesting this?

**Comment by MartaSztuka** [comment]
@openstaxalina I'll do it now and let you know ;)

**Comment by MartaSztuka** [comment]
@openstaxalina after rebaking numbers are restarting properly
![poujiougyjdg](https://user-images.githubusercontent.com/47241114/55624249-a3bfff00-57a5-11e9-82e5-dfcc34d38153.jpeg)

**Comment by openstaxalina** [comment]
@MartaSztuka I'm still not seeing the fix.  I cleared browser cache to ensure I wasn't looking at cached content.  

I'm not sure why I can see other fixes, but not this one.  I suggest that we park this on Monday's call.  I've made a note to do so.

**Comment by MartaSztuka** [comment]
@openstaxalina I agree, checked now in same place I made a print screen on Friday, now it's not fixed.

**Comment by MartaSztuka** [comment]
@openstaxalina it's fixed on feature branch, screens above

**Comment by Adrianltd** [comment]
The fix affects also `dev-math` books, it adds exercise counter-resetting on the `[data-type="composite-page"]`. 
What should be tested:
Numbering of exercises in composite-pages in `dev-math` books.

**Comment by MartaSztuka** [comment]
Issue is most probably fixed; works in Prealgebra and College Algebra, Algebra&Trigonometry still can't be baked.
![Screenshot from 2019-04-11 15-53-48](https://user-images.githubusercontent.com/47241114/55963079-66121900-5c72-11e9-9840-b351aee9e13e.png)

**Comment by Adrianltd** [comment]
As mentioned https://github.com/openstax/cnx-recipes/pull/987#discussion_r274375216 this no longer affects `dev-math`.

**Comment by uskka** [comment]
Looks good in all of the volumes. Tested on katalyst01.
<img width="1203" alt="Screenshot 2019-04-17 at 12 25 47" src="https://user-images.githubusercontent.com/40228918/56281088-01403e00-610c-11e9-967a-dbd4f35347a5.png">
